export const GET_POSTS = 'GET_POSTS'
export const UPDATE_POSTSAVALIATION = 'GET_POSTS'

export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS'
export const OPEN_NOTIFICATIONS = 'OPEN_NOTIFICATIONS'

export const OPEN_PROFILE = 'OPEN_PROFILE'
export const GET_PROFILE = 'GET_PROFILE'

export const OPEN_MENUWEHEARTIT = 'OPEN_MENUWEHEARTIT'
